# Generated by Django 6.0.5 on 2026-09-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="licence_plate",
            new_name="license_plate",
        ),
    ]
